development:
  # secret_key_base: super_long_secret_key_for_development
  secret_key_base: super_long_secret_key_for_development
  google_client_id: 835005991691-k0p507q9d560onquieaeo4esggsoetgc.apps.googleusercontent.com
  google_client_secret: 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